stages:
  - test

services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
    command: "--cluster_name NATS --cluster nats://0.0.0.0:6222 --http_port 8222"

test:
  stage: test
  image: rust:latest
  before_script:
    # install protoc if your build.rs needs it
    - |
      PROTOC_VERSION="31.1"
      PROTOC_ZIP="protoc-${PROTOC_VERSION}-linux-x86_64.zip"
      
      # Download protoc from GitHub releases
      curl -OL "https://github.com/protocolbuffers/protobuf/releases/download/v${PROTOC_VERSION}/${PROTOC_ZIP}"
      
      # Extract the binary and includes
      unzip -o "${PROTOC_ZIP}" -d /usr/local bin/protoc
      unzip -o "${PROTOC_ZIP}" -d /usr/local include/*
      
      # Clean up and verify
      rm -f "${PROTOC_ZIP}"
      protoc --version
  script:
    - cargo test --verbose
