services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
      - "8080:8080"
    command: "--config /etc/nats/nats.conf"
    volumes:
      - "./nats.conf:/etc/nats/nats.conf:ro"

  provider-1:
    image: ghcr.io/wasimoff/provider:nightly
    restart: unless-stopped
    command: ["--url", "ad://nats:8080/?announce=5", "--workers", "1"]
    depends_on:
      - nats

  provider-2:
    image: ghcr.io/wasimoff/provider:nightly
    restart: unless-stopped
    command: ["--url", "ad://nats:8080/?announce=5", "--workers", "1"]
    depends_on:
      - nats
