services:
  rabbitmq:
    image: rabbitmq:4-management
    container_name: rabbitmq
    # Enable the stream plugins before launching the server
    command: >
      bash -lc "rabbitmq-plugins enable --offline rabbitmq_stream rabbitmq_stream_management && rabbitmq-server"
    restart: always
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: password
      RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS: -rabbitmq_stream advertised_host localhost
    ports:
      - "5552:5552"      # Stream Port
      - "5672:5672"      # AMQP
      - "15672:15672"    # Management UI
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

volumes:
  rabbitmq_data:
    driver: local