services:
  nats:
    image: nats:latest
    ports:
      - "4222:4222"
      - "8222:8222"
      - "8080:8080"
    command: "--config /etc/nats/nats.conf"
    volumes:
      - "./nats.conf:/etc/nats/nats.conf:ro"
    networks: [ "nats", "default" ]

  provider:
    image: ansemjo/wasimoff:provider
    restart: unless-stopped
    command: ["--url", "http://nats:8080", "--deco"]
    networks: [ "nats", "default" ]

networks:
  nats:
    name: nats
