services:
  workspace:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile.workspace
    volumes:
      - ..:/workspaces:cached
      - /var/run/docker.sock:/var/run/docker.sock
    command: sleep infinity
