# Multi-stage build to copy directories from wasimoff/tracebench:latest
FROM ghcr.io/wasimoff/tracebench:latest AS tracebench

# Base devcontainer image
FROM mcr.microsoft.com/devcontainers/base:bullseye

# Copy /dataset and /tracebench from the tracebench image
COPY --from=tracebench /tracebench /tracebench
COPY --from=tracebench /wasm/argonload.wasm /wasm/
